import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { User } from "lucide-react";
import UserProvider from "./_context/Users";
import ProfilePaidProvider from "./_context/Paid";
import ProfileProvider from "./_context/Profile";
import { OneProfileProvider } from "./_context/OneProfile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container mx-auto bg-white text-black dark:bg-black dark:text-white`}
      >
        <OneProfileProvider>
          <ProfileProvider>
            <ProfilePaidProvider>
              <UserProvider>{children}</UserProvider>
            </ProfilePaidProvider>
          </ProfileProvider>
        </OneProfileProvider>
      </body>
    </html>
  );
}
